export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_POSTS_FULFILLED = "FETCH_POSTS_FULFILLED";
export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_FULFILLED = "CREATE_POST_FULFILLED";
export const CHANGE_ROUTE = "CHANGE_ROUTE";